---
title: Exam 02 practice
---

::: callout-important
This page contains practice problems to help prepare for Exam 01. This set of practice problems is <u>**not**</u> comprehensive.\
\
There is no answer key for these problems. You are encouraged to ask questions during office hours or on Ed Discussion.
:::

# Multiple linear (variable transformations, multicollinearity, model comparison)

## Exercise 1

Consider the model on [this slide](https://sta210-sp26.github.io/slides/13-variable-transformations.html#/interpretation) using education and income inequality to understand variability in healthcare expenditure. Note that the log-transformed response was used to fit the model.

Describe the predicted difference in healthcare between a country with `income_inequality = 30` and `education = Low` and a country with `income_inequality = 50` and `education = High`.

## Exercise 2

Consider the model on [this slide](https://sta210-sp26.github.io/slides/13-variable-transformations.html#/interpretation-2) that uses log-transformed healthcare expenditure, income inequality, and education to explain variability in life expectancy.

Describe the predicted difference in life expectancy between a country with `healthcare_expend = 2500`, `income_inequality = 30`, `education = Low` and a country with `healthcare_expend = 5000`, `income_inequality = 20`, `education = Low` .

## Exercise 3

Explain how the presence of multicollinearity impacts the model coefficients, predictions from the model, and inferences that can be made from a model.

# Logistic regression

## Exercise 4

*Adapted from Introduction to Statistical Learning*

-   On average, what fraction of people with an odds of 0.37 of defaulting on their credit card payment will in fact default?

-   Suppose an individual has a 16% chance of defaulting on their credit card payment. What are the odds they will default?

## Exercise 15

Recall the model using age and education to predict odds of being high risk for heart disease.

-   Show mathematically why the interpretation for the slope for `age` in terms of the log-odds is in the form shown on [this slide](https://sta221-sp25.netlify.app/slides/19-logistic-regression#/interpretation-in-terms-of-log-odds-1).

-   Show mathematically why the interpretation for the slope of `age` in terms of the odds is in the form shown on [this slide](https://sta221-sp25.netlify.app/slides/19-logistic-regression#/interpretation-in-terms-of-odds-1).

## Exercise 4

Write the hypotheses being tested in the drop-in-deviance test output on [this slide](https://sta221-sp25.netlify.app/slides/22-logistic-inference#/add-interactions-with-currentsmoker). Explain how each value in the table is computed.

## Exercise 13

-   What is an advantage of using a drop-in-deviance test instead of AIC (or BIC) to compare regression models?

-   What is an advantage of using AIC (or BIC) instead of a drop-in-deviance test to compare regression models?

## 

## Exercise 16

Recall the model using age and education to predict odds of being high risk for heart disease.

-   Show mathematically why the interpretation for the slope for `education4` in terms of the log-odds is in the form shown on [this slide](https://sta221-sp25.netlify.app/slides/19-logistic-regression#/interpretation-in-terms-of-log-odds).

-   Show mathematically why the interpretation for the slope of `education4`in terms of the odds is in the form shown on [this slide](https://sta221-sp25.netlify.app/slides/19-logistic-regression#/interpretation-in-terms-of-odds).

## Exercise 17

Explain why the slope of the logistic regression model is called the Adjusted Odds Ratio (or just Odds Ratio if there is one predictor).

## Exercise 18

-   Draw an example of an ROC curve such that the AUC is about 0.55

-   Draw an example of an ROC curve such that the AUC is about 0.9.

-   Explain what each point on an ROC curve represents.

# Relevant assignments and AEs

The following assignments and AEs cover Exam 02 content. Ask yourself "why" questions as your review your answers, process, and derivations on these assignments. It may also be helpful to explain your process to others.

-   HW 03, HW 04

-   Lab 05, Lab 06, Lab 07

-   AE 04, AE 05
