---
title: "Project proposal"
date: "02-23-2026"
date-format: "MMM DD, YYYY"
footer: "🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Today's agenda

Final project: Proposal

## Final project {.midi}

-   **Goal**: Use the methods from STA 210 to analyze data and answer a research question developed by your team

-   **Primary deliverables:**

    1.  an in-person presentation about your analysis and results

    2.  a written, reproducible report detailing your analysis and results

    3.  a GitHub repository containing all work from the project

-   There are periodic project milestones throughout the semester to help you work towards these deliverables

## Today's focus: Proposal {.midi}

-   **Goals:** Identify a research question and data set you're interested in investigating

-   What is due:

    -   Written proposal with a description of the research question, data set, and EDA for the response variable

    -   Data in GitHub repo

    -   Data dictionary (code book) in GitHub repo

All work for the project will be submitted on GitHub. There are no Gradescope submissions.

🔗 <https://sta210-sp26.github.io/project>
