---
title: "Lab 06"
subtitle: "Logistic regression"
date: "03-23-2026"
date-format: "MMM DD, YYYY"
footer: "🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)"
logo: "../images/logo.png"
format: 
  revealjs: 
    theme: slides.scss
    multiplex: false
    transition: fade
    slide-number: true
    incremental: false 
    chalkboard: true
    include-before: [ '<script type="text/x-mathjax-config">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']
html-math-method:
  method: mathjax
  url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
execute:
  freeze: auto
  echo: true
knitr:
  opts_chunk: 
    R.options:      
    width: 200
bibliography: references.bib
---

## Review {.midi}

A hospital is evaluating the use of a logistic regression model for detecting a disease. Below are the truth and predicted classifications for 200 patients.

|   | **Actual disease Present** | **Actual disease Absent** |
|----|----|----|
| **Classified as disease present** | 50 | 20 |
| **Classified as disease absent** | 10 | 120 |

::: question
-   Compute sensitivity and interpret it in the context of the analysis.

-   Compute specificity and interpret it in the context of the analysis.

-   Compute the false positive rate and interpret it in the context of the analysis.
:::

## Options on how to work on lab

-   Individually

-   Work with 1 - 2 other students but everyone submits their own lab assignment

-   Collaborate with 1 - 2 other students using a single GitHub repo and submit a single lab assignment (include all names)

    -   We can help you add all students to a single repo

## Today's lab

This lab focuses on using logistic regression to classify rice varieties based on data derived from images

🔗 [sta210-sp26.github.io/labs/lab-06.html](https://sta210-sp26.github.io/labs/lab-06.html)
