{
  "hash": "fe8b44d9662b1b07c8a0725f4010d54b",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"03-17-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 16-logistic-regression-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements {.midi}\n\n-   HW 03 due TODAY at 11:59pm\n\n-   Project EDA due March 24 at 11:59pm (on GitHub)\n\n-   Statistics experience due April 15\n\n-   DataFest March 20 - 22: [[https://dukestatsci.github.io/datafest/]{.underline}](https://dukestatsci.github.io/datafest/ \"https://dukestatsci.github.io/datafest/\")\n\n## Mid-semester feedback\n\n## Topics\n\n-   Logistic regression for binary response variable\n\n-   Relationship between odds and probabilities\n\n-   Odds ratios\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(Stat2Data)\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n# Predicting categorical outcomes \n\n## Types of outcome variables\n\n**Quantitative outcome variable**:\n\n-   Sales price of a house in Duke Forest\n-   **Model**: Expected sales price given the number of bedrooms, lot size, etc.\n\n. . .\n\n**Categorical outcome variable**:\n\n-   Indicator of being high risk of getting coronary heart disease in the next 10 years\n-   **Model**: Probability an adult is high risk of heart disease in the next 10 years given their age, total cholesterol, etc.\n\n## Do teenagers get 7+ hours of sleep? {.smaller}\n\n::::: columns\n::: {.column width=\"40%\"}\nStudents in grades 9 - 12 were surveyed about health risk behaviors including whether they usually get 7 or more hours of sleep.\n\n`Sleep7`\n\n1: yes\n\n0: no\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 446 × 2\n     Age Sleep7\n   <int>  <int>\n 1    16      1\n 2    17      0\n 3    18      0\n 4    17      1\n 5    15      0\n 6    17      0\n 7    17      1\n 8    16      1\n 9    16      1\n10    18      0\n# ℹ 436 more rows\n```\n\n\n:::\n:::\n\n:::\n:::::\n\n## Plot the data\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(sleep, aes(x = Age, y = Sleep7)) +\n  geom_point() + \n  labs(y = \"Getting 7+ hours of sleep\")\n```\n\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Let's fit a linear regression model\n\n**Outcome:** $Y$ = 1: yes, 0: no\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Let's use proportions\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## What happens if we zoom out?\n\n**Outcome:** Probability of getting 7+ hours of sleep\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/unnamed-chunk-7-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n🛑 *This model produces predictions outside of 0 and 1.*\n\n## Let's try another model\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/logistic-model-plot-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n*✅ This model (called a **logistic regression model**) only produces predictions between 0 and 1.*\n\n## The code\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nggplot(sleep_age, aes(x = Age, y = prop)) +\n  geom_point() + \n  geom_hline(yintercept = c(0,1), lty = 2) + \n  stat_smooth(method =\"glm\", method.args = list(family = \"binomial\"), \n              fullrange = TRUE, se = FALSE) +\n  labs(y = \"P(7+ hours of sleep)\") +\n  xlim(1, 40) +\n  ylim(-0.5, 1.5)\n```\n:::\n\n\n## Different types of models\n\n| Method | Outcome | Model |\n|------------------------|------------------------|------------------------|\n| Linear regression | Quantitative | $y_i = \\beta_0 + \\beta_1~ x_i$ |\n| Linear regression (transform Y) | Quantitative | $\\log(y_i) = \\beta_0 + \\beta_1~ x_i$ |\n| Logistic regression | Binary | $\\log\\big(\\frac{p_i}{1-p_i}\\big) = \\beta_0 + \\beta_1 ~ x_i$ |\n\n## Linear vs. logistic regression\n\n::::: panel-tabset\n## Question\n\n:::: midi\n::: question\nState whether a linear regression model or logistic regression model is more appropriate for each scenario.\n\n1.  Use age and political party to predict if a randomly selected person will vote in the next election.\n\n2.  Use budget and run time (in minutes) to predict a movie's total revenue.\n\n3.  Use age and sex to compute the probability a randomly selected adult will visit Duke Health in the next year.\n:::\n\n🔗 <https://forms.office.com/r/hvhGK4dX7t>\n::::\n\n## Submit\n\n```{=html}\n<center><iframe width=\"640px\" height=\"480px\" src=\"https://forms.office.com/r/hvhGK4dX7t?embed=true\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" style=\"border: none; max-width:100%; max-height:100vh\" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe></center>\n```\n:::::\n\n# Probabilities, odds, and odds ratios\n\n## Data: Concern about rising AI {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThis data comes from the 2023 [Pew Research Center's American Trends Panel](https://www.pewresearch.org/the-american-trends-panel/). The survey aims to capture public opinion about a variety of topics including politics, religion, and technology, among others. We will use data from 11201 respondents in Wave 132 of the survey conducted July 31 - August 6, 2023.\n\n<br>\n\n**The goal of this analysis is to understand the relationship between age, how much someone has heard about artificial intelligence (AI), and concern about the increased use of AI in daily life.**\n\n<br>\n\nA more complete analysis on this topic can be found in the Pew Research Center article [*Growing public concern about the role of artificial intelligence in daily life*](https://www.pewresearch.org/short-reads/2023/08/28/growing-public-concern-about-the-role-of-artificial-intelligence-in-daily-life/) by Alec Tyson and Emma Kikuchi.\n\n## Variables\n\n-   `ai_concern`: Whether a respondent said they are \"more concerned than excited\" about in the increased use of AI in daily life (1: yes, 0: no)\n\n![Source: Pew Research](images/18/survey-question.png){fig-align=\"center\"}\n\n## Variables {.midi}\n\n-   `ai_heard` : Response to the question \"How much have you heard or read about AI?\"\n\n    -   A lot\n    -   A little\n    -   Nothing at all\n    -   Refused\n\n-   `age_cat`: Age category\n\n    -   18-29\n    -   30-49\n    -   50-64\n    -   65+\n    -   Refused\n\n## Data prep\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# change variable names and recode categories\npew_data <- pew_data |>\n  mutate(ai_concern = if_else(CNCEXC_W132 == 2, 1, 0),\n         age_cat = case_when(F_AGECAT == 1 ~ \"18-29\",\n                             F_AGECAT == 2 ~ \"30-49\",\n                             F_AGECAT == 3 ~ \"50-64\",\n                             F_AGECAT == 4 ~ \"65+\",\n                             TRUE ~ \"Refused\"), \n         ai_heard = case_when(AI_HEARD_W132 == 1 ~ \"A lot\",\n                              AI_HEARD_W132 == 2 ~ \"A little\",\n                              AI_HEARD_W132 == 3 ~ \"Nothing at all\",\n                              TRUE ~ \"Refused\"\n                              ))\n\n# Make factors and  relevel \npew_data <- pew_data |>\n  mutate(ai_concern = factor(ai_concern),\n         age_cat = factor(age_cat), \n         ai_heard = factor(ai_heard, levels = c(\"A lot\", \"A little\", \"Nothing at all\", \"Refused\"))\n  )\n```\n:::\n\n\n## Univariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](16-logistic-regression_files/figure-revealjs/unnamed-chunk-11-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Binary response variable\n\n::: incremental\n-   $Y = 1: \\text{ yes (success), } 0: \\text{ no (failure)}$\n\n-   $p$: **probability** that $Y=1$, i.e., $P(Y = 1)$\n\n-   $\\frac{p}{1-p}$: **odds** that $Y = 1$\n\n-   $\\log\\big(\\frac{p}{1-p}\\big)$: **log odds**\n\n-   Go from $p$ to $\\log\\big(\\frac{p}{1-p}\\big)$ using the **logit transformation**\n:::\n\n## Concerned about AI in daily life?\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npew_data |>\n  count(ai_concern) |>\n  mutate(p = round(n / sum(n), 3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 2 × 3\n  ai_concern     n     p\n  <fct>      <int> <dbl>\n1 0           5245 0.468\n2 1           5956 0.532\n```\n\n\n:::\n:::\n\n\n<br>\n\n. . .\n\n$P(\\text{Concerned about AI}) = P(Y = 1) = p = 0.532$\n\n. . .\n\n$P(\\text{Not concerned about AI}) = P(Y = 0) = 1 - p = 0.468$\n\n. . .\n\n$\\text{Odds of being concerned about AI} = \\frac{0.532}{0.468} = 1.137$\n\n## From odds to probabilities\n\n::::: columns\n::: {.column width=\"50%\"}\n**odds**\n\n$$\\text{odds} = \\frac{p}{1-p}$$\n:::\n\n::: {.column width=\"50%\"}\n**probability**\n\n$$p = \\frac{\\text{odds}}{1 + \\text{odds}}$$\n:::\n:::::\n\n# Odds ratios\n\n## Concern about AI vs. age\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\n## Compare the odds for two groups {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\n. . .\n\nWe want to compare concern about increased use of AI in daily life between individuals who are 18-29 years old to those who are 65+ years old\n\n## Compare the odds for two groups\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\nWe'll use the **odds** to compare the two groups\n\n$$\n\\text{odds} = \\frac{P(\\text{success})}{P(\\text{failure})} = \\frac{\\text{# of successes}}{\\text{# of failures}}\n$$\n\n## Compare the odds for two groups {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\n::: incremental\n-   Odds of being concerned with increased use of AI in daily life for 18-29 year olds: $\\frac{416}{550} = 0.756$\n\n-   Odds of being concerned with increased use of AI in daily life for those who are 65+ years old: $\\frac{2013}{1376} = 1.463$\n\n-   Based on this, we see that individuals 65+ years old are more likely to be concerned about the increased use of AI in daily life than 18-29 year olds.\n:::\n\n## Odds ratio (OR) {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\nLet's summarize the relationship between the two groups. To do so, we'll use the **odds ratio (OR)**.\n\n$$\nOR = \\frac{\\text{odds}_1}{\\text{odds}_2}\n$$\n\n## OR: AI concern by age {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\n$$OR = \\frac{\\text{odds}_{18-29}}{\\text{odds}_{65+}} = \\frac{0.756}{1.463} = \\mathbf{0.517}$$\n\n. . .\n\nThe odds an 18-29 year old is concerned about increased use of AI in daily life are 0.517 times the odds a 65+ year old is concerned.\n\n## More natural interpretation\n\n-   It's more natural to interpret the odds ratio with a statement with the odds ratio greater than 1.\n\n-   The odds a 65+ year old is concerned about increased use of AI in daily life are 1.934 (1/0.517) times the odds an 18-29 year old is concerned.\n\n## Code to make table\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npew_data |>\n  count(age_cat, ai_concern)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 3\n   age_cat ai_concern     n\n   <fct>   <fct>      <int>\n 1 18-29   0            550\n 2 18-29   1            416\n 3 30-49   0           1898\n 4 30-49   1           1681\n 5 50-64   0           1398\n 6 50-64   1           1818\n 7 65+     0           1376\n 8 65+     1           2013\n 9 Refused 0             23\n10 Refused 1             28\n```\n\n\n:::\n:::\n\n\n## Code to make table\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"3\"}\npew_data |>\n  count(age_cat, ai_concern) |>\n  pivot_wider(names_from = ai_concern, values_from = n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  age_cat   `0`   `1`\n  <fct>   <int> <int>\n1 18-29     550   416\n2 30-49    1898  1681\n3 50-64    1398  1818\n4 65+      1376  2013\n5 Refused    23    28\n```\n\n\n:::\n:::\n\n\n## Code to make table\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\npew_data |>\n  count(age_cat, ai_concern) |>\n  pivot_wider(names_from = ai_concern, values_from = n) |>\n  kable()\n```\n\n::: {.cell-output-display}\n\n\n|age_cat |    0|    1|\n|:-------|----:|----:|\n|18-29   |  550|  416|\n|30-49   | 1898| 1681|\n|50-64   | 1398| 1818|\n|65+     | 1376| 2013|\n|Refused |   23|   28|\n\n\n:::\n:::\n\n\n## Code to make table\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"4\"}\npew_data |>\n  count(age_cat, ai_concern) |>\n  pivot_wider(names_from = ai_concern, values_from = n) |>\n  kable(col.names = c(\"Age\", \"Not concerned\", \"Concerned\"))\n```\n\n::: {.cell-output-display}\n\n\n|Age     | Not concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           550|       416|\n|30-49   |          1898|      1681|\n|50-64   |          1398|      1818|\n|65+     |          1376|      2013|\n|Refused |            23|        28|\n\n\n:::\n:::\n\n\n# Logistic regression\n\n## Logistic regression model {.incremental}\n\nLet $\\pi$ be the probability that $Y = 1$. Then the population-level **logistic regression model** is of the form\n\n$$\n\\log\\big(\\frac{\\pi}{1-\\pi}\\big) = \\beta_0 + \\beta_1~X_1 + \\beta_2X_2 + \\dots + \\beta_p X_p\n$$\n\n<br>\n\nwhere $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$ = the log odds $Y = 1$\n\n::: question\nWhy is there no error term in the population-level model?\n:::\n\n## Concern with AI model\n\nFit logistic regression models using `glm()` with the argument `family = \"binomial\"`.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_concern_model <- glm(ai_concern  ~ age_cat, data = pew_data, \n                        family = \"binomial\")\n\ntidy(ai_concern_model) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.279|     0.065|    -4.297|   0.000|\n|age_cat30-49   |    0.158|     0.073|     2.159|   0.031|\n|age_cat50-64   |    0.542|     0.074|     7.316|   0.000|\n|age_cat65+     |    0.660|     0.074|     8.939|   0.000|\n|age_catRefused |    0.476|     0.289|     1.648|   0.099|\n\n\n:::\n:::\n\n\n# Application exercise\n\n::: appex\n📋 [sta210-sp26.github.io/ae/ae-10-logistic.html](../ae/ae-10-logistic.html)\n:::\n\n## From log odds to odds\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.279|     0.065|    -4.297|   0.000|\n|age_cat30-49   |    0.158|     0.073|     2.159|   0.031|\n|age_cat50-64   |    0.542|     0.074|     7.316|   0.000|\n|age_cat65+     |    0.660|     0.074|     8.939|   0.000|\n|age_catRefused |    0.476|     0.289|     1.648|   0.099|\n\n\n:::\n:::\n\n\n::: question\n-   How do we write this model in terms of the **odds** of being comfortable with driverless cars?\n\n-   Interpret the coefficient of `Agree` in terms of the **odds** of being comfortable with driverless cars.\n\n-   Describe the interpretation between the coefficients the odds ratio.\n:::\n\n## Recap\n\n-   Introduced logistic regression for binary response variable\n\n-   Showed the relationship between odds and probabilities\n\n-   Introduced odds ratios and interpretations in the logistic regression model\n",
    "supporting": [
      "16-logistic-regression_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}