{
  "hash": "a79bdf92c754506bba1765ca3ebfada3",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Multiple linear regression\"\nsubtitle: \"Types of predictors\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"02-03-2026\"\ndate-format: \"MMMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 08-predictor-types-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\nfilters: \n  - webr\nwebr: \n  packages: ['tidyverse', 'broom', 'palmerpenguins']\n---\n\n## Announcements {.midi}\n\n-   Lab 02 due **Thursday, February 5** at 11:59pm\n-   HW 02 due Tuesday, February 10 at 11:59pm\n    -   Released after class today\n-   [Statistics experience](../hw/stats-experience.html) due April 21\n-   SSMU Mini DataFest - February 8\n    -   See [Ed Discussion](https://edstem.org/us/courses/91299/discussion/7577398) for announcement\n\n## Computational setup\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(openintro)\nlibrary(patchwork)\nlibrary(knitr)\nlibrary(kableExtra)\nlibrary(colorblindr)\nlibrary(palmerpenguins)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_minimal(base_size = 16))\n```\n:::\n\n\n```{webr-r}\n#| context: setup\n\npenguins <- palmerpenguins::penguins |>\n  select(body_mass_g, flipper_length_mm, bill_length_mm, species) |>\n  drop_na() |>\n  mutate(\n    adelie = if_else(species == \"Adelie\", 1, 0),\n    chinstrap = if_else(species == \"Chinstrap\", 1, 0),\n    gentoo = if_else(species == \"Gentoo\", 1, 0)\n  )\n```\n\n## Topics\n\n-   Include indicator variables for categorical predictors in the regression model\n\n-   Mean-center and standardize quantitative predictors\n\n-   Use interaction terms in the model to capture differences in a predictor's effect\n\n## Data: Palmer penguins {.midi}\n\nThe `penguins` data set contains data for penguins found on three islands in the Palmer Archipelago, Antarctica. Data were collected and made available by [Dr. Kristen Gorman](https://www.uaf.edu/cfos/people/faculty/detail/kristen-gorman.php) and the [Palmer Station, Antarctica LTER](https://pal.lternet.edu/), a member of the [Long Term Ecological Research Network](https://lternet.edu/). These data can be found in the **palmerpenguins** R package.\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 342 × 4\n   body_mass_g flipper_length_mm bill_length_mm species\n         <int>             <int>          <dbl> <fct>  \n 1        3750               181           39.1 Adelie \n 2        3800               186           39.5 Adelie \n 3        3250               195           40.3 Adelie \n 4        3450               193           36.7 Adelie \n 5        3650               190           39.3 Adelie \n 6        3625               181           38.9 Adelie \n 7        4675               195           39.2 Adelie \n 8        3475               193           34.1 Adelie \n 9        4250               190           42   Adelie \n10        3300               186           37.8 Adelie \n# ℹ 332 more rows\n```\n\n\n:::\n:::\n\n\n## Variables\n\n**Predictors**:\n\n-   `bill_length_mm`: Bill length in millimeters\n-   `flipper_length_mm`: Flipper length in millimeters\n-   `species`: Adelie, Gentoo, or Chinstrap species\n\n**Response**: `body_mass_g`: Body mass in grams\n\n<br>\n\n**The goal of this analysis is to use the bill length, flipper length, and species to predict body mass.**\n\n## Response: `body_mass_g`\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-2-1.png){width=960}\n:::\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|  min| median|  max|  iqr|\n|----:|------:|----:|----:|\n| 2700|   4050| 6300| 1200|\n\n\n:::\n:::\n\n\n## Predictors {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-4-1.png){width=100%}\n:::\n:::\n\n\n## Response vs. predictors {.small}\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-5-1.png){width=960}\n:::\n:::\n\n\n## Multiple linear regression model\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_fit <- lm(body_mass_g ~ flipper_length_mm + species + \n                bill_length_mm, data = penguins)\n\ntidy(penguin_fit) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term              |  estimate| std.error| statistic| p.value|\n|:-----------------|---------:|---------:|---------:|-------:|\n|(Intercept)       | -3904.387|   529.257|    -7.377|   0.000|\n|flipper_length_mm |    27.429|     3.176|     8.638|   0.000|\n|speciesChinstrap  |  -748.562|    81.534|    -9.181|   0.000|\n|speciesGentoo     |    90.435|    88.647|     1.020|   0.308|\n|bill_length_mm    |    61.736|     7.126|     8.664|   0.000|\n\n\n:::\n:::\n\n\n## Model equation\n\n$$\n\\begin{align}\\widehat{\\text{body_mass_g}} =  -3904.387 &+27.429 \\times \\text{flipper_length_mm}\\\\\n& -748.562 \\times \\text{Chinstrap}\\\\  \n&+ 90.435 \\times \\text{Gentoo}\\\\\n&+ 61.736 \\times \\text{bill_length_mm}\n\\end{align}\n$$\n\n::: callout-note\nWe will talk about why there are two terms in the model for `species` shortly!\n:::\n\n## Interpreting $\\hat{\\beta}_j$\n\n-   The estimated coefficient $\\hat{\\beta}_j$ is the expected change in the mean of $Y$ when $X_j$ increases by one unit, <i>holding the values of all other predictor variables constant</i>.\n\n<br>\n\n-   **Example:** The estimated coefficient for `flipper_length_mm` is 27.429. This means for each additional millimeter in a penguin's flipper length, its body mass is expected to be greater by 27.429 grams, on average, holding species and bill length constant.\n\n## Prediction\n\n::: question\nWhat is the predicted body mass for a Gentoo penguin with a flipper length of 200 millimeters and bill length of 45 millimeters?\n:::\n\n<br>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnew_penguin <- tibble(\n  flipper_length_mm  = 200, \n  species = \"Gentoo\", \n  bill_length_mm = 45\n)\n\npredict(penguin_fit, new_penguin)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n       1 \n4449.955 \n```\n\n\n:::\n:::\n\n\n## Intervals for prediction {.midi}\n\n90% confidence interval for **estimated mean body mass** of Gentoo penguins with flipper length of 200 mm and bill length of 45 mm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(penguin_fit, new_penguin, interval = \"confidence\", \n        level = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|      fit|      lwr|      upr|\n|--------:|--------:|--------:|\n| 4449.955| 4355.238| 4544.671|\n\n\n:::\n:::\n\n\n<br>\n\n90% prediction interval for **estimated body mass of an individual** Gentoo penguin with flipper length of 200 mm and bill length of 45 mm.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npredict(penguin_fit, new_penguin, interval = \"prediction\", \n        level = 0.90) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|      fit|      lwr|      upr|\n|--------:|--------:|--------:|\n| 4449.955| 3881.035| 5018.875|\n\n\n:::\n:::\n\n\n# Categorical predictors\n\n## Indicator variables\n\n-   Suppose there is a categorical variable with $k$ categories (levels)\n\n-   We can make $k$ indicator variables - one indicator for each category\n\n-   An **indicator variable** (also called dummy variables) takes values 1 or 0\n\n    -   1 if the observation belongs to that category\n    -   0 if the observation does not belong to that category\n\n## Indicator variables for `species`\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins <- penguins |>\n  mutate(\n    adelie = if_else(species == \"Adelie\", 1, 0),\n    chinstrap = if_else(species == \"Chinstrap\", 1, 0),\n    gentoo = if_else(species == \"Gentoo\", 1, 0)\n  )\n```\n:::\n\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 4\n  species   adelie chinstrap gentoo\n  <fct>      <dbl>     <dbl>  <dbl>\n1 Adelie         1         0      0\n2 Gentoo         0         0      1\n3 Chinstrap      0         1      0\n```\n\n\n:::\n:::\n\n\n## Indicators in the model {.midi}\n\n-   We will use $k-1$ of the indicator variables in the model.\n-   The **baseline** is the category that doesn't have a term in the model. This is also called the *reference level.*\n-   The coefficients of the indicator variables in the model are interpreted as the expected change in the response compared to the baseline, holding all other variables constant.\n\n. . .\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins |>\n  select(species, chinstrap, gentoo) |>\n  slice(1, 152, 283)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 3 × 3\n  species   chinstrap gentoo\n  <fct>         <dbl>  <dbl>\n1 Adelie            0      0\n2 Gentoo            0      1\n3 Chinstrap         1      0\n```\n\n\n:::\n:::\n\n\n## Using all $k$ indicators in R model\n\n::: question\nRun the code below to fit a model using `flipper_length_mm`, `bill_length_mm`, and all the indicator variables for `species` to predict `body_mass_g`. What do you notice about the model output? Why did this happen?\n:::\n\n```{webr-r}\nbody_mass_fit <- lm(body_mass_g ~ flipper_length_mm + bill_length_mm + \n                      adelie + chinstrap + gentoo,\n                    data = penguins)\n\ntidy(body_mass_fit)\n```\n\n## Interpreting `species` {.midi}\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n   <th style=\"text-align:right;\"> conf.low </th>\n   <th style=\"text-align:right;\"> conf.high </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -3904.387 </td>\n   <td style=\"text-align:right;\"> 529.257 </td>\n   <td style=\"text-align:right;\"> -7.377 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> -4945.450 </td>\n   <td style=\"text-align:right;\"> -2863.324 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flipper_length_mm </td>\n   <td style=\"text-align:right;\"> 27.429 </td>\n   <td style=\"text-align:right;\"> 3.176 </td>\n   <td style=\"text-align:right;\"> 8.638 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 21.182 </td>\n   <td style=\"text-align:right;\"> 33.675 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> speciesChinstrap </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -748.562 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 81.534 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -9.181 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.000 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -908.943 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -588.182 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> speciesGentoo </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 90.435 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 88.647 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 1.020 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.308 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -83.937 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 264.807 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bill_length_mm </td>\n   <td style=\"text-align:right;\"> 61.736 </td>\n   <td style=\"text-align:right;\"> 7.126 </td>\n   <td style=\"text-align:right;\"> 8.664 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n   <td style=\"text-align:right;\"> 47.720 </td>\n   <td style=\"text-align:right;\"> 75.753 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n. . .\n\n::: incremental\n-   The baseline category is `Adelie`.\n-   Penguins from the Chinstrap species are expected to have a body mass that is 748.562 grams less, on average, compared to penguins from the Adelie species, holding flipper length and bill length constant.\n:::\n\n. . .\n\n::: question\nInterpret the coefficient of `Gentoo` in the context of the data.\n:::\n\n# Transforming quantitative predictors\n\n## Centering {.midi}\n\n-   Centering a quantitative predictor means shifting every value by some constant $C$\n\n$$\nX_{cent} = X  - C\n$$\n\n-   One common type of centering is **mean-centering**, in which every value of a predictor is shifted by its mean\n\n-   Only quantitative predictors are centered\n\n-   Center all quantitative predictors in the model for ease of interpretation, when using mean-centering\n\n::: question\nWhat is one reason we might want to center the quantitative predictors? What are the units of centered variables?\n:::\n\n## Centering {.midi}\n\nUse the `scale()` function with `center = TRUE` and `scale = FALSE` to mean-center variables\n\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\npenguins <- penguins |>\n  mutate(flipper_length_cent = scale(flipper_length_mm, center = TRUE, scale = FALSE), \n         bill_length_cent = scale(bill_length_mm, center = TRUE, scale = FALSE))\n```\n:::\n\n\n## Original vs. mean-centered variable\n\n::::: columns\n::: {.column width=\"50%\"}\n**Original variable**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|    Mean|     SD|\n|-------:|------:|\n| 200.915| 14.062|\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Mean-centered variable**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Mean|     SD|\n|----:|------:|\n|    0| 14.062|\n\n\n:::\n:::\n\n:::\n:::::\n\n<br>\n\n. . .\n\n## Using mean-centered variables in the model\n\n::: question\nHow do you expect the model to change if we use `flipper_length_cent` and `bill_length_cent` in the model?\n:::\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:-------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)         | 4318.066|    45.674|    94.542|   0.000| 4228.225|  4407.908|\n|flipper_length_cent |   27.429|     3.176|     8.638|   0.000|   21.182|    33.675|\n|speciesChinstrap    | -748.562|    81.534|    -9.181|   0.000| -908.943|  -588.182|\n|speciesGentoo       |   90.435|    88.647|     1.020|   0.308|  -83.937|   264.807|\n|bill_length_cent    |   61.736|     7.126|     8.664|   0.000|   47.720|    75.753|\n\n\n:::\n:::\n\n\n## Original vs. mean-centered model {.midi}\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              |  estimate|\n|:-----------------|---------:|\n|(Intercept)       | -3904.387|\n|flipper_length_mm |    27.429|\n|speciesChinstrap  |  -748.562|\n|speciesGentoo     |    90.435|\n|bill_length_mm    |    61.736|\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                | estimate|\n|:-------------------|--------:|\n|(Intercept)         | 4318.066|\n|flipper_length_cent |   27.429|\n|speciesChinstrap    | -748.562|\n|speciesGentoo       |   90.435|\n|bill_length_cent    |   61.736|\n\n\n:::\n:::\n\n:::\n:::::\n\n::: question\nWhat changed? What is the same?\n:::\n\n## Interpret coefficient of mean-centered predictors\n\n::::: panel-tabset\n## Question\n\n:::: midi\n::: appex\nInterpret the coefficient of `bill_length_cent` in the context of the data.\n:::\n\n🔗 <https://forms.office.com/r/Cn8pp2r32U>\n::::\n\n## Submit\n\n```{=html}\n<center><iframe width=\"640px\" height=\"480px\" src=\"https://forms.office.com/r/Cn8pp2r32U?embed=true\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" style=\"border: none; max-width:100%; max-height:100vh\" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe></center>\n```\n:::::\n\n## Standardizing {.midi}\n\n-   Standardizing a quantitative predictor mean shifting every value by the mean and dividing by the standard deviation of that variable\n\n$$\nX_{std} = \\frac{X - \\bar{X}}{s_X}\n$$\n\n-   Only quantitative predictors are standardized\n\n-   Standardize all quantitative predictors in the model for ease of interpretation\n\n::: question\nWhat is one reason we might want to standardize the quantitative predictors? What are the units of standardized variables?\n:::\n\n## Standardizing\n\nUse the `scale()` function with `center = TRUE` and `scale = TRUE` to standardized variables\n\n<br>\n\n\n::: {.cell output-location='fragment'}\n\n```{.r .cell-code}\npenguins <- penguins |>\n  mutate(flipper_length_std = scale(flipper_length_mm, center = TRUE, scale = TRUE), \n         bill_length_std = scale(bill_length_mm, center = TRUE, scale = TRUE))\n```\n:::\n\n\n## Original vs. standardized variable\n\n::::: columns\n::: {.column width=\"50%\"}\n**Original variable**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-23-1.png){width=960}\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|    Mean|     SD|\n|-------:|------:|\n| 200.915| 14.062|\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n**Standardized variable**\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-25-1.png){width=960}\n:::\n:::\n\n\n<br>\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n| Mean| SD|\n|----:|--:|\n|    0|  1|\n\n\n:::\n:::\n\n:::\n:::::\n\n<br>\n\n. . .\n\n## Using standardized variables in the model\n\n::: question\nHow do you expect the model to change if we use `flipper_length_std` and `bill_length_std` in the model?\n:::\n\n. . .\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term               | estimate| std.error| statistic| p.value| conf.low| conf.high|\n|:------------------|--------:|---------:|---------:|-------:|--------:|---------:|\n|(Intercept)        | 4318.066|    45.674|    94.542|   0.000| 4228.225|  4407.908|\n|flipper_length_std |  385.696|    44.654|     8.638|   0.000|  297.862|   473.531|\n|speciesChinstrap   | -748.562|    81.534|    -9.181|   0.000| -908.943|  -588.182|\n|speciesGentoo      |   90.435|    88.647|     1.020|   0.308|  -83.937|   264.807|\n|bill_length_std    |  337.055|    38.902|     8.664|   0.000|  260.533|   413.577|\n\n\n:::\n:::\n\n\n## Original vs. standardized model\n\n::::: columns\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              |  estimate|\n|:-----------------|---------:|\n|(Intercept)       | -3904.387|\n|flipper_length_mm |    27.429|\n|speciesChinstrap  |  -748.562|\n|speciesGentoo     |    90.435|\n|bill_length_mm    |    61.736|\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"50%\"}\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term               | estimate|\n|:------------------|--------:|\n|(Intercept)        | 4318.066|\n|flipper_length_std |  385.696|\n|speciesChinstrap   | -748.562|\n|speciesGentoo      |   90.435|\n|bill_length_std    |  337.055|\n\n\n:::\n:::\n\n:::\n:::::\n\n::: question\nWhat changed? What is the same?\n:::\n\n# Interaction terms\n\n## Interaction terms\n\n-   Sometimes the relationship between a predictor variable and the response depends on the value of another predictor variable.\n-   This is an **interaction effect**.\n-   To account for this, we can include **interaction terms** in the model.\n\n## Bill length versus species\n\nIf the lines are not parallel, there is indication of a potential **interaction effect**, i.e., the slope of bill length may differ based on the species.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](08-predictor-types_files/figure-revealjs/unnamed-chunk-30-1.png){width=960}\n:::\n:::\n\n\n## Interaction terms in R {.midi}\n\n::: question\nFit the model with the predictors `flipper_length_mm`, `bill_length_mm`, `speices`, and the interaction between\n\n-   Write the estimated regression equation for `Adelie` penguins.\n\n-   Write the estimated regression equation for `Chinstrap` penguins.\n:::\n\n```{webr-r}\n\n# code to fit and display model with interaction\n```\n\n## Interaction term in model {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguin_int_fit <- lm(body_mass_g ~ flipper_length_mm + species + bill_length_mm + species * bill_length_mm,\n      data = penguins)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n`````{=html}\n<table>\n <thead>\n  <tr>\n   <th style=\"text-align:left;\"> term </th>\n   <th style=\"text-align:right;\"> estimate </th>\n   <th style=\"text-align:right;\"> std.error </th>\n   <th style=\"text-align:right;\"> statistic </th>\n   <th style=\"text-align:right;\"> p.value </th>\n  </tr>\n </thead>\n<tbody>\n  <tr>\n   <td style=\"text-align:left;\"> (Intercept) </td>\n   <td style=\"text-align:right;\"> -4297.905 </td>\n   <td style=\"text-align:right;\"> 645.054 </td>\n   <td style=\"text-align:right;\"> -6.663 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> flipper_length_mm </td>\n   <td style=\"text-align:right;\"> 27.263 </td>\n   <td style=\"text-align:right;\"> 3.175 </td>\n   <td style=\"text-align:right;\"> 8.586 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> speciesChinstrap </td>\n   <td style=\"text-align:right;\"> 1146.287 </td>\n   <td style=\"text-align:right;\"> 726.217 </td>\n   <td style=\"text-align:right;\"> 1.578 </td>\n   <td style=\"text-align:right;\"> 0.115 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> speciesGentoo </td>\n   <td style=\"text-align:right;\"> 54.716 </td>\n   <td style=\"text-align:right;\"> 619.934 </td>\n   <td style=\"text-align:right;\"> 0.088 </td>\n   <td style=\"text-align:right;\"> 0.930 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;\"> bill_length_mm </td>\n   <td style=\"text-align:right;\"> 72.692 </td>\n   <td style=\"text-align:right;\"> 10.642 </td>\n   <td style=\"text-align:right;\"> 6.831 </td>\n   <td style=\"text-align:right;\"> 0.000 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> speciesChinstrap:bill_length_mm </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -41.035 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 16.104 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -2.548 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.011 </td>\n  </tr>\n  <tr>\n   <td style=\"text-align:left;background-color: rgba(220, 229, 178, 255) !important;\"> speciesGentoo:bill_length_mm </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -1.163 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 14.436 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> -0.081 </td>\n   <td style=\"text-align:right;background-color: rgba(220, 229, 178, 255) !important;\"> 0.936 </td>\n  </tr>\n</tbody>\n</table>\n\n`````\n:::\n:::\n\n\n## Interpreting interaction terms\n\n-   What the interaction means: The effect of bill length on the body mass is 41.035 less when the penguin is from the Chinstrap species compared to the effect for the Adelie species, holding all else constant.\n-   Interpreting `bill_length_mm` for Chinstrap: For each additional millimeter in bill length, we expect the body mass of Chinstrap penguins to increase by 31.657 grams (72.692 - 41.035), holding flipper length constant.\n\n## Summary\n\n<br>\n\n::: question\nIn general, how do\n\nindicators for categorical predictors impact the model equation?\n\ninteraction terms impact the model equation?\n:::\n\n## Recap\n\n-   Included indicator variables for categorical predictors in the regression model\n\n-   Mean-centered and standardized quantitative predictors\n\n-   Used interaction terms in the model to capture differences in a predictor's effect\n\n## Next class\n\n-   Inference for multiple linear regression\n\n-   Complete [Lecture 09 prepare](../prepare/prepare-lec09.html)\n",
    "supporting": [
      "08-predictor-types_files/figure-revealjs"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<script src=\"../site_libs/kePrint-0.0.1/kePrint.js\"></script>\n<link href=\"../site_libs/lightable-0.0.1/lightable.css\" rel=\"stylesheet\" />\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}