{
  "hash": "330cf1586b687c1e610af251fbdac285",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression\"\nsubtitle: \"Prediction + Assessment\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"03-19-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 17-logistic-prediction-notes.html\n    resources: \n      - \"framingham.csv\"\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\nfilters: \n  - webr\nwebr:\n  packages: ['tidyverse', 'broom', 'yardstick'] \n---\n\n\n\n## Announcements {.midi}\n\n-   Project EDA due March 24 at 11:59pm (on GitHub)\n\n-   Statistics experience due April 15\n\n**Submit questions by the end of the day. Form at the end of today’s notes.**\n\n## Topics\n\n-   Interpreting logistic regression models\n\n-   Relationship between odds and probabilities\n\n-   Odds ratios\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\nlibrary(patchwork)\nlibrary(ggridges) # for ridgeline plots\nlibrary(RColorBrewer)\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n## Data: Concern about rising AI {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\nThis data comes from the 2023 [Pew Research Center's American Trends Panel](https://www.pewresearch.org/the-american-trends-panel/). The survey aims to capture public opinion about a variety of topics including politics, religion, and technology, among others. We will use data from 11201 respondents in Wave 132 of the survey conducted July 31 - August 6, 2023.\n\n<br>\n\n**The goal of this analysis is to understand the relationship between age, time to complete the survey, and concern about the increased use of AI in daily life.**\n\n<br>\n\nA more complete analysis on this topic can be found in the Pew Research Center article [*Growing public concern about the role of artificial intelligence in daily life*](https://www.pewresearch.org/short-reads/2023/08/28/growing-public-concern-about-the-role-of-artificial-intelligence-in-daily-life/) by Alec Tyson and Emma Kikuchi.\n\n## Variables\n\n-   `ai_concern`: Whether a respondent said they are \"more concerned than excited\" about in the increased use of AI in daily life (1: yes, 0: no)\n\n![Source: Pew Research](images/18/survey-question.png){fig-align=\"center\"}\n\n## Variables {.midi}\n\n-   `age_cat`: Age category\n\n    -   18-29\n    -   30-49\n    -   50-64\n    -   65+\n    -   Refused\n\n-   `survey_time`: Time to complete the survey (in minutes)\n\n## Data prep\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# change variable names and recode categories\npew_data <- pew_data |>\n  mutate(ai_concern = if_else(CNCEXC_W132 == 2, 1, 0),\n         age_cat = case_when(F_AGECAT == 1 ~ \"18-29\",\n                             F_AGECAT == 2 ~ \"30-49\",\n                             F_AGECAT == 3 ~ \"50-64\",\n                             F_AGECAT == 4 ~ \"65+\",\n                             TRUE ~ \"Refused\"\n))\n\n# Make factors and  relevel \npew_data <- pew_data |>\n  mutate(ai_concern = factor(ai_concern),\n         age_cat = factor(age_cat))\n\n# compute the time it took to do the interview\npew_data <- pew_data |>\n  mutate(\n    start_time = ymd_hms(INTERVIEW_START_W132),\n    end_time = ymd_hms(INTERVIEW_END_W132),\n    survey_time = as.numeric(difftime(end_time, start_time, units = \"mins\"))\n)\n  \npew_data <- \n  pew_data |> filter(survey_time <= 70)\n```\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = pew_data, aes(x = age_cat, fill = ai_concern)) + \n  geom_bar(position = \"fill\", color = \"black\") +\n  labs(x = \"\",\n       y = \"Proportion\",\n       title = \"AI Concern versus Age\", \n       fill = \"AI Concern\") +\n  scale_fill_brewer(palette = \"Dark2\")\n```\n\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-5-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = pew_data, aes(x = survey_time, y = ai_concern, \n                                  fill = ai_concern)) + \n  geom_density_ridges() +\n  theme_ridges() + \n  labs(title = \"AI concern versus survey time\", \n         x = \"Survey time in minutes\", \n         y = \"AI concern\",\n       fill = \"AI concern\") +\n  theme(legend.position = \"none\") +\n  scale_fill_brewer(palette = \"Dark2\") \n```\n\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-6-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Logistic regression model {.incremental}\n\nLet $\\pi$ be the probability that $Y = 1$. Then the population-level **logistic regression model** is of the form\n\n$$\n\\log\\big(\\frac{\\pi}{1-\\pi}\\big) = \\beta_0 + \\beta_1~X_1 + \\beta_2X_2 + \\dots + \\beta_p X_p\n$$\n\n<br>\n\nwhere $\\log\\big(\\frac{\\pi}{1-\\pi}\\big)$ = the log odds $Y = 1$\n\n## AI concern versus age\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_concern_fit <- glm(ai_concern ~ age_cat, data = pew_data, \n                      family = \"binomial\")\n\ntidy(ai_concern_fit) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n\n## The model {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n\n\\\n$$\\begin{aligned}\\log\\Big(\\frac{\\hat{\\pi}}{1-\\hat{\\pi}}\\Big) =& -0.248 + 0.126\\times\\text{age_cat30-49} + 0.538 \\times \\text{age_cat50-64}\\\\ \n&+ 0.643 \\times \\text{age_cat65+} + 0.493\\times \\text{age_catRefused} \\end{aligned}$$\n\nwhere $\\hat{\\pi}$ is the predicted probability of being concerned about increased use of AI in daily life\n\n## Interpreting `age_cat30-49`: log-odds\n\n::: small\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n:::\n\nThe predicted **log-odds** of being concerned about increased use of AI in daily life are 0.126 higher for individuals 30 - 49 years old compared to 18-29 year-olds (the baseline group).\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpreting `age_cat30-49`: odds\n\n::: small\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n:::\n\nThe predicted **odds** of being concerned about increased use of AI in daily life for 30 - 49 year-olds are 1.134 ( $e^{0.126}$ ) times the odds for 18-29 year-olds.\n\n## Coefficients & odds ratios\n\nThe model coefficient, 0.126, is the expected difference in the log-odds when comparing 30 - 49 year olds to 18 - 29 year olds.\n\n. . .\n\nTherefore, $e^{0.126}$ = 1.134 is the expected change in the **odds** when comparing 30 - 49 year olds to 18-29 year olds.\n\n. . .\n\n$$\nOR  = e^{\\hat{\\beta}_j} = \\exp\\{\\hat{\\beta}_j\\}\n$$\n\n## Interpret in terms of percent change\n\nYou can also interpret the change in the odds in terms of a percent change. The percent change in the odds can be computed as the following\n\n$$\\% \\text{ change } = (e^{\\hat{\\beta}_j} - 1) \\times 100$$\n\n<br>\n\n::: question\nInterpret the coefficient of `age_cat30-49` (0.126) in terms of the percent change in the odds.\n:::\n\n## Quantitative predictor\n\nNow let's look at the relationship between `survey_time` and `ai_concern`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_time_fit <- glm(ai_concern ~ survey_time, data = pew_data,\nfamily = \"binomial\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    0.069|     0.037|     1.853|   0.064|\n|survey_time |    0.005|     0.002|     2.434|   0.015|\n\n\n:::\n:::\n\n\n. . .\n\nFor each additional minute of taking the survey, the predicted odds of being concerned about increased AI in daily life multiply by a factor of 1.005 ( $e^{0.005}$).\n\n## Multiple predictors\n\nNow let's consider a model that takes into account `age` and `survey_time`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_concern_full_fit <- glm(ai_concern ~ age_cat  + survey_time, data = pew_data, family = \"binomial\")\n```\n:::\n\n\n## Multiple predictors {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.240|     0.073|    -3.281|   0.001|\n|age_cat30-49   |    0.127|     0.077|     1.640|   0.101|\n|age_cat50-64   |    0.541|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.647|     0.079|     8.217|   0.000|\n|age_catRefused |    0.497|     0.322|     1.543|   0.123|\n|survey_time    |   -0.001|     0.002|    -0.330|   0.742|\n\n\n:::\n:::\n\n\n<br>\n\n::: question\n-   Describe the type of respondent represented by the intercept.\n-   Interpret the coefficient of `survey_time` in the context of the data.\n:::\n\n## Displaying logistic model in R\n\nBy default, `tidy()` displays the model in terms of $\\log\\big(\\frac{\\hat{\\pi}}{1 - \\hat{\\pi}}\\big)$ . Use argument `exponentiate = TRUE` to display the model in terms of the odds.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\ntidy(ai_concern_full_fit, exponentiate = TRUE) |>\n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |    0.787|     0.073|    -3.281|   0.001|\n|age_cat30-49   |    1.135|     0.077|     1.640|   0.101|\n|age_cat50-64   |    1.717|     0.078|     6.904|   0.000|\n|age_cat65+     |    1.910|     0.079|     8.217|   0.000|\n|age_catRefused |    1.644|     0.322|     1.543|   0.123|\n|survey_time    |    0.999|     0.002|    -0.330|   0.742|\n\n\n:::\n:::\n\n\n# Prediction\n\n## Data: Risk of coronary heart disease\n\nThis data set is from an ongoing cardiovascular study on residents of the town of Framingham, Massachusetts.\n\n-   `high_risk`: 1 = High risk of having heart disease in next 10 years, 0 = Not high risk of having heart disease in next 10 years\n\n-   `age`: Age at exam time (in years)\n\n-   `totChol`: Total cholesterol (in mg/dL)\n\n-   `currentSmoker`: 0 = nonsmoker; 1 = smoker\n\n**The goal is to use logistic regression to identify patients who are high risk of heart disease.**\n\n## Univariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Modeling risk of coronary heart disease\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_fit <- glm(high_risk ~ age + totChol + currentSmoker, \n              data = heart_disease, family = \"binomial\")\n\ntidy(heart_disease_fit) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -6.638|     0.372|   -17.860|   0.000|\n|age            |    0.082|     0.006|    14.430|   0.000|\n|totChol        |    0.002|     0.001|     2.001|   0.045|\n|currentSmoker1 |    0.457|     0.092|     4.951|   0.000|\n\n\n:::\n:::\n\n\n## Prediction and classification\n\n::: incremental\n-   We are often interested in using the model to classify observations, i.e., predict whether a given observation will have a 1 or 0 response\n\n-   For each observation\n\n    -   Use the logistic regression model to calculate the predicted log-odds the response for the $i^{th}$ observation is 1\n    -   Use the log-odds to calculate the predicted probability the $i^{th}$ observation is 1\n    -   Then, use the predicted probability to classify the observation as having a 1 or 0 response using some predefined threshold\n:::\n\n## Augmented data frame\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_aug <- augment(heart_disease_fit)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 4,190 × 10\n   high_risk   age totChol currentSmoker .fitted .resid     .hat .sigma  .cooksd\n   <fct>     <dbl>   <dbl> <fct>           <dbl>  <dbl>    <dbl>  <dbl>    <dbl>\n 1 0            39     195 0              -3.06  -0.302 0.000594  0.890  6.94e-6\n 2 0            46     250 0              -2.38  -0.420 0.000543  0.890  1.25e-5\n 3 0            48     245 1              -1.77  -0.560 0.000527  0.890  2.24e-5\n 4 1            61     225 1              -0.751  1.51  0.00164   0.889  8.70e-4\n 5 0            46     285 1              -1.86  -0.539 0.000830  0.890  3.25e-5\n 6 0            43     228 0              -2.67  -0.366 0.000546  0.890  9.43e-6\n 7 1            63     205 0              -1.08   1.66  0.00154   0.889  1.15e-3\n 8 0            45     313 1              -1.88  -0.532 0.00127   0.890  4.86e-5\n 9 0            52     260 0              -1.87  -0.535 0.000542  0.890  2.08e-5\n10 0            43     225 1              -2.22  -0.454 0.000532  0.890  1.44e-5\n# ℹ 4,180 more rows\n# ℹ 1 more variable: .std.resid <dbl>\n```\n\n\n:::\n:::\n\n\n## Predicted log-odds\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 1\n  .fitted\n    <dbl>\n1  -3.06 \n2  -2.38 \n3  -1.77 \n4  -0.751\n5  -1.86 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Observation 1**\n\n$$\n\\log(\\hat{\\text{odds}}) = \\log\\Big(\\frac{\\hat{\\pi}}{1- \\hat{\\pi}}\\Big) = -3.06\n$$\n\n## Predicted odds\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 1\n  .fitted\n    <dbl>\n1  -3.06 \n2  -2.38 \n3  -1.77 \n4  -0.751\n5  -1.86 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Observation 1**\n\n$$\n\\hat{\\text{odds}} = \\frac{\\hat{\\pi}}{1- \\hat{\\pi}} = \\exp\\{-3.06\\} = 0.0469\n$$\n\n## Predicted probability\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 1\n  .fitted\n    <dbl>\n1  -3.06 \n2  -2.38 \n3  -1.77 \n4  -0.751\n5  -1.86 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**Observation 1**\n\n$$\n\\text{predicted prob.} = \\hat{\\pi} = \\frac{\\hat{\\text{odds}}}{1+\\hat{\\text{odds}}} = \\frac{\\exp\\{-3.06\\}}{1 + \\exp\\{-3.06\\}}= 0.045\n$$\n\n## Classifying observations\n\n::::: panel-tabset\n## Question\n\n:::: midi\n::: question\n1.  An individual has a predicted probability of 0.045. Would you consider this person high risk for heart disease?\n2.  An individual has a predicted probability of 0.321. Would you consider this person high risk for heart disease?\n:::\n\n🔗 <https://forms.office.com/r/VPjCMfrsLy>\n::::\n\n## Submit\n\n```{=html}\n<center><iframe width=\"640px\" height=\"480px\" src=\"https://forms.office.com/r/VPjCMfrsLy?embed=true\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" style=\"border: none; max-width:100%; max-height:100vh\" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe></center>\n```\n:::::\n\n## Predicted probabilities in R\n\nCompute predicted probabilities by adding `type.predict = \"response\"` argument in `augment()`\n\n<br>\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_aug <- augment(heart_disease_fit, type.predict = \"response\")\n```\n:::\n\n\n. . .\n\n**Predicted probabilities for Observations 1 -5**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 6 × 1\n  .fitted\n    <dbl>\n1  0.0446\n2  0.0845\n3  0.145 \n4  0.321 \n5  0.135 \n6  0.0646\n```\n\n\n:::\n:::\n\n\n## Classifying observations\n\n::: question\nYou would like to determine a threshold for classifying individuals as high risk or not high risk.\n\nWhat considerations would you make in determining the threshold?\n:::\n\n## Classify using 0.5 as threshold\n\nWe can use a threshold of 0.5 to classify observations.\n\n-   If $\\hat{\\pi} > 0.5$, classify as 1\n\n-   If $\\hat{\\pi} \\leq 0.5$, classify as 0\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_aug <- heart_disease_aug |>\n  mutate(pred_class = factor(if_else(.fitted > 0.5, 1, 0)))\n```\n:::\n\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 3\n  high_risk .fitted pred_class\n  <fct>       <dbl> <fct>     \n1 0          0.0446 0         \n2 0          0.0845 0         \n3 0          0.145  0         \n4 1          0.321  0         \n5 0          0.135  0         \n```\n\n\n:::\n:::\n\n\n## Confusion matrix\n\nA **confusion matrix** is a $2 \\times 2$ table that compares the predicted and actual classes. We can produce this matrix using the `conf_mat()` function in the **yardstick** package (part of tidymodels).\n\n<br>\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_aug |>\n  conf_mat(high_risk, pred_class) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction    0    1\n         0 3553  635\n         1    2    0\n```\n\n\n:::\n:::\n\n\n## Visualize confusion matrix\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_conf_mat <- heart_disease_aug |>\n  conf_mat(high_risk, pred_class)\n\nautoplot(heart_conf_mat, type = \"heatmap\") \n```\n\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-28-1.png){fig-align='center' width=90%}\n:::\n:::\n\n\n## Using the confusion matrix\n\n::: center\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction    0    1\n         0 3553  635\n         1    2    0\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n. . .\n\nThe **accuracy** of this model with a classification threshold of 0.5 is\n\n$$\n\\text{accuracy} = \\frac{3553 + 0}{3553 + 635 + 2 + 0} = 0.848\n$$\n\n## Using the confusion matrix\n\n::: center\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction    0    1\n         0 3553  635\n         1    2    0\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\n. . .\n\nThe **misclassification rate** of this model with a threshold of 0.5 is\n\n$$\n\\text{misclassification} = \\frac{635 + 2}{3553 + 635 + 2 + 0} = 0.152\n$$\n\n## Using the confusion matrix\n\n::: center\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction    0    1\n         0 3553  635\n         1    2    0\n```\n\n\n:::\n:::\n\n:::\n\n<br>\n\nAccuracy is 0.848 and the misclassification rate is 0.152.\n\n. . .\n\n::: question\n-   What is the limitation of solely relying on accuracy and misclassification to assess the model performance?\n\n-   What is the limitation of using a single confusion matrix to assess the model performance?\n:::\n\n## Changing threshold\n\n```{webr-r}\n#| context: setup\n\nurl <- \"https://sta210-sp26.github.io/slides/data/framingham.csv\"\ndownload.file(url, \"framingham.csv\")\n\nheart_disease <- read_csv(\"framingham.csv\") |>\n  select(age, totChol, TenYearCHD, currentSmoker) |>\n  drop_na() |>\n  mutate(high_risk = as_factor(TenYearCHD), \n         currentSmoker = as_factor(currentSmoker))\n\nheart_disease_fit <- glm(high_risk ~ age + totChol + currentSmoker, \n              data = heart_disease, family = \"binomial\")\n```\n\n```{webr-r}\nthreshold <- 0.5\n\nheart_disease_aug <- augment(heart_disease_fit, type.predict = \"response\") |>\n  mutate(pred_class = factor(if_else(.fitted > threshold, 1, 0)))\n\nheart_disease_aug |>\n  conf_mat(high_risk, pred_class) \n```\n\n<br>\n\n::: question\nWhat is the limitation of using a single confusion matrix to assess the model performance?\n:::\n\n# Sensitivity and specificity\n\n## True/false positive/negative {.midi}\n\n|   | <u>Not</u> high risk $(y_i = 0)$ | High risk $(y_i = 1)$ |\n|----|----|----|\n| **Classified** <u>**not**</u> **high risk** $(\\hat{\\pi}_i \\leq \\text{threshold})$ | True negative (TN) | False negative (FN) |\n| **Classified high risk** $(\\hat{\\pi}_i > \\text{threshold})$ | False positive (FP) | True positive (TP) |\n\n<br>\n\n-   $\\text{accuracy} = \\frac{TN + TP}{TN + TP + FN + FP}$\n\n-   $\\text{misclassification} = \\frac{FN + FP}{TN+ TP + FN + FP}$\n\n## False negative rate {.midi}\n\n|   | Not high risk $(y_i = 0)$ | High risk $(y_i = 1)$ |\n|----|----|----|\n| **Classified not high risk** $(\\hat{\\pi}_i \\leq \\text{threshold})$ | True negative (TN) | False negative (FN) |\n| **Classified high risk** $(\\hat{\\pi}_i > \\text{threshold})$ | False positive (FP) | True positive (TP) |\n\n<br>\n\n. . .\n\n**False negative rate**: Proportion of actual positives that were classified as negatives\n\n-   P(classified not high risk \\| high risk) = $\\frac{FN}{TP + FN}$\n\n## False positive rate {.midi}\n\n|   | Not high risk $(y_i = 0)$ | High risk $(y_i = 1)$ |\n|----|----|----|\n| **Classified not high risk** $(\\hat{\\pi}_i \\leq \\text{threshold})$ | True negative (TN) | False negative (FN) |\n| **Classified high risk** $(\\hat{\\pi}_i > \\text{threshold})$ | False positive (FP) | True positive (TP) |\n\n<br>\n\n. . .\n\n**False positive rate**: Proportion of actual negatives that were classified as positives\n\n-   P(classified high risk \\| not high risk) = $\\frac{FP}{TN + FP}$\n\n## Sensitivity {.midi}\n\n|   | Not high risk $(y_i = 0)$ | High risk $(y_i = 1)$ |\n|----|----|----|\n| **Classified not high risk** $(\\hat{\\pi}_i \\leq \\text{threshold})$ | True negative (TN) | False negative (FN) |\n| **Classified high risk** $(\\hat{\\pi}_i > \\text{threshold})$ | False positive (FP) | True positive (TP) |\n\n<br>\n\n. . .\n\n**Sensitivity**: Proportion of actual positives that were correctly classified as positive\n\n-   Also known as *true positive rate* (TPR) and *recall*\n\n-   **P(classified high risk \\| high risk) = 1 − False negative rate**\n\n## Specificity {.midi}\n\n|   | Not high risk $(y_i = 0)$ | High risk $(y_i = 1)$ |\n|----|----|----|\n| **Classified not high risk** $(\\hat{\\pi}_i \\leq \\text{threshold})$ | True negative (TN) | False negative (FN) |\n| **Classified high risk** $(\\hat{\\pi}_i > \\text{threshold})$ | False positive (FP) | True positive (TP) |\n\n<br>\n\n. . .\n\n**Specificity**: Proportion of actual negatives that were correctly classified as negative\n\n-   **P(classified not high risk \\| not high risk) = 1 − False positive rate**\n\n## Practice\n\n::: center\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n          Truth\nPrediction    0    1\n         0 3553  635\n         1    2    0\n```\n\n\n:::\n:::\n\n:::\n\n::: question\nCalculate the\n\n-   False negative rate\n-   False positive rate\n-   Sensitivity\n-   Specificity\n:::\n\n## Using metrics to select model and threshold {.midi}\n\n+----------------------------------+---------------------------------------------------------------------+\n| Metric                           | Guidance for use                                                    |\n+==================================+=====================================================================+\n| Accuracy                         | For balanced data, use only in combination with other metrics.      |\n|                                  |                                                                     |\n|                                  | Avoid using for imbalanced data.                                    |\n+----------------------------------+---------------------------------------------------------------------+\n| Sensitivity (true positive rate) | Use when false negatives are more \"expensive\" than false positives. |\n+----------------------------------+---------------------------------------------------------------------+\n| False positive rate              | Use when false positives are more \"expensive\" than false negatives. |\n+----------------------------------+---------------------------------------------------------------------+\n| Precision = $\\frac{TP}{TP + FP}$ | Use when it's important for positive predictions to be accurate.    |\n+----------------------------------+---------------------------------------------------------------------+\n\n::: small\nThis table is a modification of work created and shared by Google in the [Google Machine Learning Crash Course](#0).\n:::\n\n## Choosing a classification threshold\n\n::: question\nA doctor plans to use your model to determine which patients are high risk for heart disease. The doctor will recommend a treatment plan for high risk patients.\n\n-   Would you want sensitivity to be high or low? What about specificity?\n\n-   What are the trade-offs associated with each decision?\n:::\n\n## ROC curve\n\nSo far the model assessment has depended on the model and selected threshold. The **receiver operating characteristic (ROC) curve** allows us to assess the model performance across a range of thresholds.\n\n. . .\n\n::::: columns\n::: {.column width=\"65%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-33-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n\n::: {.column width=\"35%\"}\n-   x-axis: 1 - Specificity (False positive rate)\n\n-   y-axis: Sensitivity (True positive rate)\n\nWhich corner of the plot indicates the best model performance?\n:::\n:::::\n\n## ROC curve\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-34-1.png){fig-align='center' width=100%}\n:::\n:::\n\n\n## ROC curve in R {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# calculate sensitivity and specificity at each threshold\nroc_curve_data <- heart_disease_aug |>\n  roc_curve(high_risk, .fitted, \n            event_level = \"second\") \n\n# plot roc curve\nautoplot(roc_curve_data)\n```\n:::\n\n\n## ROC curve in R\n\n::::: columns\n::: {.column width=\"40%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 20 × 3\n   .threshold specificity sensitivity\n        <dbl>       <dbl>       <dbl>\n 1  -Inf         0                  1\n 2     0.0259    0                  1\n 3     0.0262    0.000281           1\n 4     0.0283    0.000844           1\n 5     0.0287    0.00113            1\n 6     0.0290    0.00141            1\n 7     0.0297    0.00169            1\n 8     0.0302    0.00197            1\n 9     0.0307    0.00225            1\n10     0.0310    0.00253            1\n11     0.0313    0.00309            1\n12     0.0320    0.00338            1\n13     0.0320    0.00366            1\n14     0.0323    0.00422            1\n15     0.0325    0.00450            1\n16     0.0327    0.00478            1\n17     0.0331    0.00506            1\n18     0.0333    0.00534            1\n19     0.0334    0.00591            1\n20     0.0334    0.00619            1\n```\n\n\n:::\n:::\n\n:::\n\n::: {.column width=\"60%\"}\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](17-logistic-prediction_files/figure-revealjs/unnamed-chunk-37-1.png){fig-align='center' width=90%}\n:::\n:::\n\n:::\n:::::\n\n## Area under the curve\n\nThe **area under the curve (AUC)** can be used to assess how well the logistic model fits the data\n\n-   AUC=0.5: model is a very bad fit (no better than a coin flip)\n\n-   AUC close to 1: model is a good fit\n\n. . .\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nheart_disease_aug |>\n  roc_auc(high_risk, .fitted,\n    event_level = \"second\"\n  )\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.696\n```\n\n\n:::\n:::\n\n\n## Recap\n\n-   Interpreted coefficients of logistic regression\n\n-   Calculated predicted probabilities from the logistic regression model\n\n-   Used predicted probabilities to classify observations\n\n-   Made decisions and assessed model performance using\n\n    -   Confusion matrix\n    -   ROC curve\n\n## Questions about content?\n\n```{=html}\n<center>\n  <iframe width=\"640px\" height=\"480px\" src=\"https://forms.office.com/r/QvBy4yvV8N?embed=true\" frameborder=\"0\" marginwidth=\"0\" marginheight=\"0\" style=\"border: none; max-width:100%; max-height:100vh\" allowfullscreen webkitallowfullscreen mozallowfullscreen msallowfullscreen> </iframe>\n</center>\n```\n\n🔗 <https://forms.office.com/r/QvBy4yvV8N>\n\n## Next class\n\n-   Inference for logistic regression\n\n-   Complete [Lecture 18 prepare](../prepare/prepare-lec18.html)\n",
    "supporting": [
      "17-logistic-prediction_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}