{
  "hash": "a075bc8bf79352098a2f3dafb070d1f2",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Lab 03\"\nsubtitle: \"Multiple linear regression\"\ndate: \"02-09-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\n  warning: false\n  message: false\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n::: {.cell}\n\n:::\n\n\n## Goals\n\n-   Practice: Inference for multiple linear regression\n-   Team workflow\n-   Lab 03: Candy competition\n\n# Inference for multiple linear regression\n\n## Data: NCAA Football expenditures {.midi}\n\nToday's data come from [Equity in Athletics Data Analysis](https://ope.ed.gov/athletics/#/datafile/list) and includes information about sports expenditures and revenues for colleges and universities in the United States. This data set was featured in a [March 2022 Tidy Tuesday](https://github.com/rfordatascience/tidytuesday/blob/master/data/2022/2022-03-29/readme.md).\n\nWe will focus on the 2019 - 2020 season expenditures on football for 127 institutions in the NCAA - Division 1 FBS. The variables are :\n\n-   `total_exp_m`: Total expenditures on football in the 2019 - 2020 academic year (in millions USD)\n\n-   `enrollment_th`: Total student enrollment in the 2019 - 2020 academic year (in thousands)\n\n-   `type`: institution type (Public or Private)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfootball <- read_csv(\"data/ncaa-football-exp.csv\")\n```\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\np1 <- ggplot(data = football, aes(x = enrollment_th, y = total_exp_m)) +\n  geom_point() + \n  labs(x = \"Enrollment (in thousands)\", \n       y = \"Total expenditures (in millions)\", \n       title = \"Football expenditures vs. enrollment\")\n\np2 <- ggplot(data = football, aes(x = type, y = total_exp_m)) +\n  geom_boxplot() + \n  labs(x = \"Institution type\", \n       y = \"Total expenditures (in millions)\", \n       title = \"Football expenditures vs. institution type\")\n\np1 + p2\n```\n\n::: {.cell-output-display}\n![](lab-03_files/figure-revealjs/unnamed-chunk-3-1.png){width=960}\n:::\n:::\n\n\n## Potential interaction effect?\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nggplot(data = football, aes(x = enrollment_th, y = total_exp_m, color = type,\n                            linetype = type)) +\n  geom_point(alpha = 0.7) + \n  geom_smooth(method = \"lm\", se = FALSE) +\n  labs(x = \"Enrollment (in thousands)\", \n       y = \"Total expenditures (in millions)\", \n       title = \"Football expenditures vs. enrollment\",\n       subtitle = \"by institution type\", \n       color = \"Type\", \n       linetype = \"Type\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](lab-03_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n## Inference {.midi}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfootball_fit <- lm(total_exp_m ~ enrollment_th + type + enrollment_th * type, \n                   data = football)\n\ntidy(football_fit) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                     | estimate| std.error| statistic| p.value|\n|:------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)              |   28.487|     4.856|     5.866|    0.00|\n|enrollment_th            |   -0.056|     0.370|    -0.151|    0.88|\n|typePublic               |  -24.038|     5.523|    -4.353|    0.00|\n|enrollment_th:typePublic |    0.915|     0.387|     2.364|    0.02|\n\n\n:::\n:::\n\n\n::: question\nLet's look at the test for `enrollment_th:typePublic`.\n\n-   State the null and alternative hypotheses being tested in the model output.\n\n-   Explain what `std.error = 0.387` quantifies.\n\n-   Explain how the test statistic `2.364` is computed and what it means in the context of the data.\n:::\n\n## Inference {.midi}\n\n\n::: {.cell}\n\n```{.r .cell-code  code-fold=\"true\"}\nfootball_fit <- lm(total_exp_m ~ enrollment_th + type + enrollment_th * type, \n                   data = football)\n\ntidy(football_fit) |> \n  kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term                     | estimate| std.error| statistic| p.value|\n|:------------------------|--------:|---------:|---------:|-------:|\n|(Intercept)              |   28.487|     4.856|     5.866|    0.00|\n|enrollment_th            |   -0.056|     0.370|    -0.151|    0.88|\n|typePublic               |  -24.038|     5.523|    -4.353|    0.00|\n|enrollment_th:typePublic |    0.915|     0.387|     2.364|    0.02|\n\n\n:::\n:::\n\n\n::: question\n-   State the distribution used to compute the p-value.\n\n-   The coefficient of `enrollment_th:typePublic` has a low p-value but the coefficient for `enrollment_th` has a high p-value. What does this mean about the relationship between football expenditures and enrollment?\n:::\n\n## Meet your team!\n\n-   [**Click here**](https://prodduke-my.sharepoint.com/:x:/g/personal/mt324_duke_edu/IQBOyCiOAbuCTaSDqSwx5e17AXQXY39VvMy2szPYTCGCMUY?e=muOdca) to find your team for this week's lab.\n\n-   Sit with your team.\n\n## Team workflow\n\n-   Only <u>**one**</u> team member should type at a time. There are markers in today's lab to help you determine whose turn it is to type.\n\n    -   Every team member should still be engaged in discussion for all questions, even if it's not your turn type.\n\n-   Don't forget to **pull** to get your teammates' updates before making changes to the `.qmd` file.\n\n    ::: callout-important\n    **Only one submission per team on Gradescope. Read the submission instructions carefully!**\n    :::\n\n## Team workflow, in action\n\n-   Complete the \"Workflow: Using Git and GitHub as a team\" section of the lab in your teams.\n-   Raise your hand if you have any questions about the workflow.\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n```{=html}\n<div class=\"countdown\" id=\"timer_43dea404\" data-update-every=\"1\" tabindex=\"0\" style=\"right:0;bottom:0;font-size:2em;\">\n<div class=\"countdown-controls\"><button class=\"countdown-bump-down\">&minus;</button><button class=\"countdown-bump-up\">&plus;</button></div>\n<code class=\"countdown-time\"><span class=\"countdown-digits minutes\">05</span><span class=\"countdown-digits colon\">:</span><span class=\"countdown-digits seconds\">00</span></code>\n</div>\n```\n\n:::\n:::\n\n\n## Tips for working on a team {.midi}\n\n-   Do not pressure each other to finish early; use the time wisely to really learn the material and produce a quality report.\n\n-   The labs are structured to help you learn the steps of a data analysis. Do not split up the lab among the team members; work on it together in its entirety.\n\n-   Everyone has something to contribute! Use the lab groups as an opportunity to share ideas and learn from each other.\n\n## Today's lab\n\nIn today's lab, your team will compare multiple models to find the best one to describe what makes a good candy.\n\n🔗 <https://sta210-sp26.github.io/labs/lab-03.html>\n",
    "supporting": [
      "lab-03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../site_libs/countdown-0.4.0/countdown.css\" rel=\"stylesheet\" />\n<script src=\"../site_libs/countdown-0.4.0/countdown.js\"></script>\n"
      ],
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}