{
  "hash": "b76ec5a44a8f0991e93e44055a38b4ca",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \" Variable transformations\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"02-26-2026\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"🔗 [sta210-sp26.github.io](https://sta210-sp26.github.io)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 13-variable-transformations-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n## Announcements\n\n-   Project proposal **due TODAY** at 11:59pm on GitHub\n\n-   SSMU Mini DataFest #2: February 27 - March 1. [Click here](https://edstem.org/us/courses/91299/discussion/7720540) for announcement\n\n-   March 20 - 22: ASA DataFest at Duke\n\n    -   Learn more and register: <https://dukestatsci.github.io/datafest/#signup> \n\n## Computing set up\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)  \nlibrary(tidymodels)  \nlibrary(knitr)       \nlibrary(patchwork)\n\n# set default theme in ggplot2\nggplot2::theme_set(ggplot2::theme_bw())\n```\n:::\n\n\n## Topics\n\n-   Log-transformation on the response\n-   Log-transformation on the predictor\n\n# Variable transformations\n\n## Data: Life expectancy in 140 countries\n\n\n::: {.cell}\n\n:::\n\n\nThe data set comes from @zarulli2021 who analyze the effects of a country's healthcare expenditures and other factors on the country's life expectancy. The data are originally from the [Human Development Database](http://hdr.undp.org/en/data) and [World Health Organization](https://apps.who.int/nha/database/).\n\nThere are 140 countries (observations) in the data set.\n\n::: aside\n[Click here](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0253450) for the original research paper.\n:::\n\n## Variables\n\n-   `life_exp`: The average number of years that a newborn could expect to live, if he or she were to pass through life exposed to the sex- and age-specific death rates prevailing at the time of his or her birth, for a specific year, in a given country, territory, or geographic income_inequality. ( from the [World Health Organization](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/65#:~:text=Definition%3A,%2C%20territory%2C%20or%20geographic%20area.))\n\n-   `income_inequality`: Measure of the deviation of the distribution of income among individuals or households within a country from a perfectly equal distribution. A value of 0 represents absolute equality, a value of 100 absolute inequality (based on Gini coefficient). (from @zarulli2021)\n\n## Variables\n\n-   `education`: Indicator of whether a country’s education index is above (`High`) or below (`Low`) the median index for the 140 countries in the data set.\n\n    -   Education index: *Average of mean years of schooling (of adults) and expected years of school (of children), both expressed as an index obtained by scaling wit the corresponding maxima.*\n\n-   `health_expend`: Per capita current spending on on healthcare goods and services, expressed in respective currency - international Purchasing Power Parity (PPP) dollar ([from the World Health Organization](https://www.who.int/data/gho/indicator-metadata-registry/imr-details/4952))\n\n## Exploratory data analysis\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-3-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Exploratory data analysis\n\n**The goal is to use income inequality and education to understand variability in health expenditure**\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-4-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Original model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth_fit <- lm(health_expenditure ~ income_inequality + education, \n                     data = health_data)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              | estimate| std.error| statistic| p.value|\n|:-----------------|--------:|---------:|---------:|-------:|\n|(Intercept)       | 2070.599|   534.653|     3.873|   0.000|\n|income_inequality |  -64.346|    18.626|    -3.455|   0.001|\n|educationHigh     | 1039.298|   359.736|     2.889|   0.004|\n\n\n:::\n:::\n\n\n## Original model: Residuals vs. fitted\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n::: question\nWhat model assumption(s) appear to be violated?\n:::\n\n## Consider different transformations...\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n# Transformation on $Y$\n\n## Identifying a need to transform Y {.midi}\n\n::: incremental\n-   Typically, a “fan-shaped” residual plot indicates the need for a transformation of the response variable Y\n\n    -   There are multiple ways to transform a variable, e.g., $Y^{1/2}$, $1/Y$, $\\log(Y)$ . These are called **variance stabilizing transformations**\n\n    -   $\\log(Y)$ the most straightforward to interpret, so we use that transformation when possible\n\n-   When building a model:\n\n    -   Choose a transformation and build the model on the transformed data\n\n    -   Reevaluate the residual plots\n\n    -   If the residuals plots did not sufficiently improve, try a new transformation!\n:::\n\n## Log transformation on $Y$\n\n-   If we apply a log transformation to the response variable, we want to estimate the parameters for the statistical model\n\n$$\n\\log(Y) = \\beta_0 + \\beta_1X_1 + \\beta_2X_2 + \\dots + \\beta_pX_p + \\epsilon, \\quad \\epsilon \\sim N(0, \\sigma^2_{\\epsilon})\n$$\n\n-   The regression equation is\n\n$$\\widehat{\\log(Y)} = \\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\hat{\\beta}_2X_2 + \\dots + \\hat{\\beta}_pX_p \n$$\n\n## Distribution of $Y$and $\\log(Y)$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Model with log(Y)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhealth_logy_fit <- lm(log(health_expenditure) ~ income_inequality + education, \n                      data = health_data)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              | estimate| std.error| statistic| p.value|\n|:-----------------|--------:|---------:|---------:|-------:|\n|(Intercept)       |    7.096|     0.324|    21.895|       0|\n|income_inequality |   -0.065|     0.011|    -5.714|       0|\n|educationHigh     |    1.117|     0.218|     5.121|       0|\n\n\n:::\n:::\n\n\n<br>\n\n$$\\begin{aligned}\n\\log(\\text{health_expend}) = 7.096 &- 0.065  \\times \\text{income_inequality} \\\\\n&+ 1.117 \\times \\text{educationHigh}\n\\end{aligned}$$\n\n## Model with log(Y): Residuals\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n## Compare residual plots\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n## Transform back to $Y$\n\nWe fit the model in terms of $\\log(\\mathbf{Y})$ but want to interpret the model in terms of the original variable $Y$ , so we need to write the regression equation in terms of $Y$\n\n$$\n\\begin{aligned}\n&\\widehat{\\log(Y)} = \\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\hat{\\beta}_2X_2 + \\dots + \\hat{\\beta}_pX_p \n \\\\[8pt]\n\\Rightarrow \\quad &\\hat{Y} = e^{(\\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\hat{\\beta}_2X_2 + \\dots + \\hat{\\beta}_pX_p)}\n\\end{aligned}\n$$\n\n## Rules of log and exponential {background-color=\"#ccddeb\"}\n\n$$\n\\begin{aligned}\n\\log(ab) &= \\log(a) + \\log(b) \\\\[8pt]\n\\log\\big(\\frac{a}{b}\\big) &= \\log(a) - \\log(b)\\\\[15pt]\ne^{a + b + c} &= e^ae^be^c \\\\[8pt]\ne^{a - b} &= \\frac{e^a}{e^b}\n\\end{aligned}\n$$\n\n## Model interpretation\n\n$$\\begin{align}\\hat{y_i} &= e^{(\\hat{\\beta}_0 + \\hat{\\beta}_1 x_{i1} + \\dots + \\hat{\\beta}_Px_{ip})} \\\\ \n&= e^{\\hat{\\beta}_0}e^{\\hat{\\beta}_1x_{i1}}\\dots e^{\\hat{\\beta}_px_{ip}}\\end{align}$$\n\n. . .\n\n-   **Intercept**: When $x_{i1} = \\dots = x_{ip} =0$, $y_i$ is expected to be $e^{\\hat{\\beta}_0}$\n\n-   **Coefficient of** $X_j$: For every one unit increase in $x_{ij}$, $y_{i}$ is expected to multiply by a factor of $e^{\\hat{\\beta}_j}$, holding all else constant.\n\n## Interpretation\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term              | estimate| std.error| statistic| p.value|\n|:-----------------|--------:|---------:|---------:|-------:|\n|(Intercept)       |    7.096|     0.324|    21.895|       0|\n|income_inequality |   -0.065|     0.011|    -5.714|       0|\n|educationHigh     |    1.117|     0.218|     5.121|       0|\n\n\n:::\n:::\n\n\n:::: question\n::: midi\nInterpret each of the following in terms of the original units of health expenditure\n\n-   Intercept\n\n-   `income_inequality`\n\n-   `education`\n:::\n::::\n\n## Poll question\n\n# Log transformation on a predictor variable\n\n## Variability in life expectancy\n\nNow let's consider a model using a country's healthcare expenditure, income inequality, and education to predict its life expectancy\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-15-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Bivariate EDA\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-16-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Original model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_exp_fit <- lm(life_exp ~ health_expenditure + income_inequality + education, \n                   data = health_data)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term               | estimate| std.error| statistic| p.value|\n|:------------------|--------:|---------:|---------:|-------:|\n|(Intercept)        |   78.575|     1.775|    44.274|   0.000|\n|health_expenditure |    0.001|     0.000|     4.522|   0.000|\n|income_inequality  |   -0.484|     0.061|    -7.900|   0.000|\n|educationHigh      |    2.020|     1.168|     1.730|   0.086|\n\n\n:::\n:::\n\n\n## Original model: Residuals\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-19-1.png){width=960}\n:::\n:::\n\n\n## Residuals vs. predictors\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-20-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n. . .\n\n::: question\nThere is a non-linear relationship is between health expenditure and life expectancy.\n:::\n\n## Log Transformation on $X$\n\nTry a transformation on $X$ if the scatterplot in EDA shows non-linear relationship and residuals vs. predictor make parabola\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-21-1.png){fig-align='center' width=960}\n:::\n:::\n\n\n## Model with Transformation on $X_j$ {.midi}\n\nIf we fit a model with predictor $\\log(X_j)$, we fit a model of the form\n\n$$\nY = \\beta_0 + \\beta_1X_1 + \\dots + \\beta_j\\log(X_j) + \\dots \\beta_pX_p + \\epsilon, \\quad \\epsilon \\sim N(0, \\sigma^2_{\\epsilon})$$\n\n. . .\n\nThe estimated regression model is\n\n$$\n\\begin{aligned}\n&\\hat{Y} = \\hat{\\beta}_0 + \\hat{\\beta}_1X_1 + \\dots + \\hat{\\beta}_j\\log(X_j) + \\dots \\hat{\\beta}_pX_p \\\\[8pt]\n\\Rightarrow \\quad &\\hat{y}_i = \\hat{\\beta}_0 + \\hat{\\beta}_1x_{i1} + \\ldots + \\hat{\\beta}_j\\log(x_{ij}) + \\dots + \\hat{\\beta}_px_{ip} \n\\end{aligned}\n$$\n\n## Distribution of $X_j$and $\\log(X_j)$\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-22-1.png){width=960}\n:::\n:::\n\n\n## Model with $\\log(X_j)$ \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlife_exp_logx_fit <- lm(life_exp ~ log(health_expenditure) + income_inequality + education, \n                        data = health_data)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                    | estimate| std.error| statistic| p.value|\n|:-----------------------|--------:|---------:|---------:|-------:|\n|(Intercept)             |   59.151|     3.184|    18.576|   0.000|\n|log(health_expenditure) |    3.092|     0.396|     7.814|   0.000|\n|income_inequality       |   -0.362|     0.058|    -6.225|   0.000|\n|educationHigh           |   -0.168|     1.103|    -0.152|   0.879|\n\n\n:::\n:::\n\n\n$$\n\\begin{aligned}\n\\text{life_exp} = 78.575 &+ 0.001 \\times \\log(\\text{health_expend})\\\\\n& - 0.484 \\times \\text{income_inequality} \\\\ \n&+ 0.020 \\times \\text{educationHigh}\n\\end{aligned}\n$$\n\n## Model with log(X): Residuals\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-25-1.png){width=960}\n:::\n:::\n\n\n## Compare residual plots \n\n\n::: {.cell}\n::: {.cell-output-display}\n![](13-variable-transformations_files/figure-revealjs/unnamed-chunk-26-1.png){width=960}\n:::\n:::\n\n\n## Model interpretation {.midi}\n\n$$\n\\hat{y}_i = \\hat{\\beta}_0 + \\hat{\\beta}_1x_{i1} + \\ldots + \\hat{\\beta}_j\\log(x_{ij}) + \\dots + \\hat{\\beta}_px_{ip} \n$$\n\n::: incremental\n-   **Intercept:** When $x_{i1} = \\dots = \\log(x_{ij}) = \\dots = x_{ip} = 0$ , $y_i$ is expected to be $\\hat{\\beta}_0$, on average, holding all else constant.\n\n    -   $\\log(x_{ij}) = 0$ when $x_{ij} = 1$\n\n-   **Coefficient of** $X_j$**:** When $x_{ij}$ is multiplied by a factor of $C$, $y_i$ is expected to change by $\\hat{\\beta}_1\\log(C)$ units, on average, holding all else constant.\n\n    -   **Example**: When $x_{ij}$ is multiplied by a factor of 2, $y_i$ is expected to increase by $\\hat{\\beta}_1\\log(2)$ units, on average, holding all else constant.\n:::\n\n## Interpretation {.midi}\n\n\n::: {.cell}\n::: {.cell-output-display}\n\n\n|term                    | estimate| std.error| statistic| p.value|\n|:-----------------------|--------:|---------:|---------:|-------:|\n|(Intercept)             |   59.151|     3.184|    18.576|   0.000|\n|log(health_expenditure) |    3.092|     0.396|     7.814|   0.000|\n|income_inequality       |   -0.362|     0.058|    -6.225|   0.000|\n|educationHigh           |   -0.168|     1.103|    -0.152|   0.879|\n\n\n:::\n:::\n\n\n<br>\n\n::: question\n-   Interpret the intercept in the context of the data.\n\n-   Interpret the effect of health expenditure in the context of the data.\n\n-   Interpret the effect of education in the context of the data.\n:::\n\n## Learn more\n\nSee [Appendix A.9](https://intro-regression.github.io/appendix-linear.html#sec-var-transformations-math) for more mathematical details.\n\n## Recap\n\n-   Introduced log-transformation on the response to address violations in equal variance\n-   Introduced log-transformation on the predictor to address non-linearity\n\n## Next class\n\n-   Model selection\n\n-   Complete [Lecture 14 prepare](../prepare/prepare-lec14.html)\n\n## References\n",
    "supporting": [
      "13-variable-transformations_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}