{
  "hash": "48b574f5e4dfaef03c1a8607256ccb91",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Logistic regression\"\nauthor: \"Prof. Maria Tackett\"\ndate: \"2025-03-20\"\ndate-format: \"MMM DD, YYYY\"\nfooter: \"[🔗 STA 210 - Spring 2025](https://sta210-sp25.netlify.app)\"\nlogo: \"../images/logo.png\"\nformat: \n  revealjs: \n    theme: slides.scss\n    multiplex: false\n    transition: fade\n    slide-number: true\n    incremental: false \n    chalkboard: true\n    include-before: [ '<script type=\"text/x-mathjax-config\">MathJax.Hub.Config({tex2jax: {enableAssistiveMml: false}});</script>']\n  html: \n    output-file: 17-logistic-regression-notes.html\nhtml-math-method:\n  method: mathjax\n  url: \"https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js\"\nexecute:\n  freeze: auto\n  echo: true\nknitr:\n  opts_chunk: \n    R.options:      \n    width: 200\nbibliography: references.bib\n---\n\n\n\n## Announcements\n\n-   Exploratory data analysis due TODAY at 11:59pm\n\n    -   Next milestone: Project presentations March 31 in lab\n\n-   Statistics experience due April 15\n\n## Topics\n\n::: nonincremental\n-   Odds and probabilities\n\n-   Interpret the coefficients of a logistic regression model with\n\n    -   a single categorical predictor\n    -   a single quantitative predictor\n    -   multiple predictors\n:::\n\n## Computational setup\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\n# load packages\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(knitr)\n\n# set default theme and larger font size for ggplot2\nggplot2::theme_set(ggplot2::theme_bw(base_size = 20))\n```\n:::\n\n\n## Probabilities vs. odds[^1] {.midi}\n\n[^1]:\n    ::: small\n    This example is from @ledolter2003statistical .\n    :::\n\n**Scenario 1**: Suppose the probability of a disease among a population of unvaccinated individuals is 0.00369, and the probability of the disease is 0.001 among a population of vaccinated individuals.\n\n**Scenario 2**: Suppose the probability of a disease among a population of unvaccinated individuals is 0.48052 and the probability of the disease is 0.2 among a population of vaccinated individuals.\n\n::: question\n-   What is the difference in the probability of disease for these two populations?\n\n-   What are the odds of disease in the population without a vaccine relative to the odds of disease in the with vaccine?\n:::\n\n# Logistic regression\n\n## From odds to probabilities\n\n::::: columns\n::: {.column width=\"50%\"}\n**odds**\n\n$$\\text{odds} = \\frac{p}{1-p}$$\n:::\n\n::: {.column width=\"50%\"}\n**probability**\n\n$$p = \\frac{\\text{odds}}{1 + \\text{odds}}$$\n:::\n:::::\n\n## From odds to probabilities {.incremental}\n\n::: incremental\n(1) **Logistic model**: $\\log\\big(\\frac{p}{1-p}\\big) = \\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p$\n\n(2) **Odds =** $\\exp\\big\\{\\log\\big(\\frac{p}{1-p}\\big)\\big\\} = \\frac{p}{1-p}$\n\n(3) Combining (1) and (2) with what we saw earlier\n:::\n\n. . .\n\n$$p = \\frac{\\exp\\{\\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p\\}}{1 + \\exp\\{\\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p\\}}$$\n\n## Logistic regression model\n\n**Logit form**: $$\\log\\Big(\\frac{p}{1-p}\\Big) = \\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p$$\n\n. . .\n\n**Probability form**:\n\n$$\n\\text{probability} = p = \\frac{\\exp\\{\\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p\\}}{1 + \\exp\\{\\beta_0 + \\beta_1~X_1 + \\dots + \\beta_pX_p\\}}\n$$\n\n::: question\nWhy is there no error term $\\epsilon$ when writing the statistical model for logistic regression?\n:::\n\n## Data: Concern about rising AI {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stderr}\n\n```\nRows: 11201 Columns: 140\n── Column specification ────────────────────────────────────────────────────────\nDelimiter: \",\"\ndbl  (138): QKEY, DEVICE_TYPE_W132, LANG_W132, FORM_W132, XDENOM_W132, IMPWO...\ndttm   (2): INTERVIEW_START_W132, INTERVIEW_END_W132\n\nℹ Use `spec()` to retrieve the full column specification for this data.\nℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n\n\n:::\n:::\n\n\nThis data comes from the 2023 [Pew Research Center's American Trends Panel](https://www.pewresearch.org/the-american-trends-panel/). The survey aims to capture public opinion about a variety of topics including politics, religion, and technology, among others. We will use data from respondents in Wave 132 of the survey conducted July 31 - August 6, 2023 *who completed the survey in 70 minutes or less.*\n\n<br>\n\n**The goal of this analysis is to understand the relationship between age, how much someone has heard about artificial intelligence (AI), and concern about the increased use of AI in daily life.**\n\n<br>\n\nA more complete analysis on this topic can be found in the Pew Research Center article [*Growing public concern about the role of artificial intelligence in daily life*](https://www.pewresearch.org/short-reads/2023/08/28/growing-public-concern-about-the-role-of-artificial-intelligence-in-daily-life/) by Alec Tyson and Emma Kikuchi.\n\n## Variables\n\n-   `ai_concern`: Whether a respondent said they are \"more concerned than excited\" about in the increased use of AI in daily life (1: yes, 0: no)\n\n## Variables\n\n-   `survey_time`: Time to complete the survey (in minutes)\n\n-   `age_cat`: Age category\n\n    -   18-29\n    -   30-49\n    -   50-64\n    -   65+\n    -   Refused\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n## Odds ratios: Concern about AI vs. age\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|Age     | Not Concerned| Concerned|\n|:-------|-------------:|---------:|\n|18-29   |           487|       380|\n|30-49   |          1661|      1470|\n|50-64   |          1257|      1680|\n|65+     |          1252|      1858|\n|Refused |            18|        23|\n\n\n:::\n:::\n\n\n## Let's fit the model\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code  code-line-numbers=\"1|2|3\"}\nai_concern_fit <- glm(ai_concern ~ age_cat, data = pew_data, \n                      family = \"binomial\")\n\ntidy(ai_concern_fit) |> kable(digits = 3)\n```\n\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n\n## The model {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n\n\\\n$$\\begin{aligned}\\log\\Big(\\frac{\\hat{p}}{1-\\hat{p}}\\Big) =& -0.248 + 0.126\\times\\text{age_cat30-49} + 0.538 \\times \\text{age_cat50-64}\\\\ \n&+ 0.643 \\times \\text{age_cat65+} + 0.493\\times \\text{age_catRefused} \\end{aligned}$$\n\nwhere $\\hat{p}$ is the predicted probability of being concerned about increased use of AI in daily life\n\n## Interpreting `age_cat30-49`: log-odds\n\n::: small\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term           | estimate| std.error| statistic| p.value|\n|:--------------|--------:|---------:|---------:|-------:|\n|(Intercept)    |   -0.248|     0.068|    -3.625|   0.000|\n|age_cat30-49   |    0.126|     0.077|     1.630|   0.103|\n|age_cat50-64   |    0.538|     0.078|     6.904|   0.000|\n|age_cat65+     |    0.643|     0.078|     8.284|   0.000|\n|age_catRefused |    0.493|     0.322|     1.531|   0.126|\n\n\n:::\n:::\n\n:::\n\nThe **log-odds** of being concerned about increased use of AI in daily life are expected to be 0.126 higher for individuals 30 - 49 years old compared to 18-29 year-olds (the baseline group).\n\n. . .\n\n::: callout-warning\nWe would not use the interpretation in terms of log-odds in practice.\n:::\n\n## Interpreting `age_cat30-49`: odds\n\n::: small\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n:::\n\nThe **odds** of being concerned about increased use of AI in daily life for 30 - 49 year olds are expected to be 1.134 ( $e^{0.126}$ ) times the odds for 18-29 year olds.\n\n## Coefficients & odds ratios\n\nThe model coefficient, 0.126, is the expected difference in the log-odds when comparing 30 - 49 year olds to 18 - 29 year olds.\n\n. . .\n\nTherefore, $e^{0.126}$ = 1.134 is the expected change in the **odds** when comparing 30 - 49 year olds to 18-29 year olds.\n\n. . .\n\n$$\nOR  = e^{\\hat{\\beta}_j} = \\exp\\{\\hat{\\beta}_j\\}\n$$\n\n## Interpret in terms of percent change\n\nYou can also interpret the change in the odds in terms of a percent change. The percent change in the odds can be computed as the following\n\n$$\\% \\text{ change } = (e^{\\hat{\\beta}_j} - 1) \\times 100$$\n\n<br>\n\n::: question\nInterpret the coefficient of `age_cat30-49` (0.126) in terms of the percent change in the odds.\n:::\n\n## Quantitative predictor\n\nNow let's look at the relationship between `survey_time` and `ai_concern`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_time_fit <- glm(ai_concern ~ survey_time, data = pew_data,\nfamily = \"binomial\")\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term        | estimate| std.error| statistic| p.value|\n|:-----------|--------:|---------:|---------:|-------:|\n|(Intercept) |    0.069|     0.037|     1.853|   0.064|\n|survey_time |    0.005|     0.002|     2.434|   0.015|\n\n\n:::\n:::\n\n\n. . .\n\nFor each additional minute of taking the survey, the odds of being concerned about increased AI in daily life are expected to multiply by a factor of 1.005 ( $e^{0.005}$).\n\n## Multiple predictors\n\nNow let's consider a model that takes into account `age` , `ai_heard` and `survey_time`\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nai_concern_full_fit <- glm(ai_concern ~ age_cat + ai_heard + \n                             survey_time, data = pew_data, family = \"binomial\")\n```\n:::\n\n\n## Multiple predictors {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n\n\n|term                   | estimate| std.error| statistic| p.value|\n|:----------------------|--------:|---------:|---------:|-------:|\n|(Intercept)            |   -0.405|     0.077|    -5.230|   0.000|\n|age_cat30-49           |    0.117|     0.078|     1.504|   0.132|\n|age_cat50-64           |    0.519|     0.079|     6.587|   0.000|\n|age_cat65+             |    0.604|     0.079|     7.611|   0.000|\n|age_catRefused         |    0.557|     0.325|     1.716|   0.086|\n|ai_heardA little       |    0.371|     0.043|     8.654|   0.000|\n|ai_heardNothing at all |   -0.243|     0.085|    -2.876|   0.004|\n|ai_heardRefused        |   -0.571|     0.505|    -1.131|   0.258|\n|survey_time            |   -0.001|     0.002|    -0.369|   0.712|\n\n\n:::\n:::\n\n\n## Interpretation\n\n<br>\n\n::: question\nUse the model on the previous slide.\n\n-   Describe the type of respondent represented by the intercept.\n-   Interpret the effect of `ai_heardNothing at all` in terms of the odds of being concerned by increased use of AI in daily life.\n:::\n\n# Prediction\n\n## Predicted log odds {.midi}\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\naugment(ai_concern_full_fit) |> select(.fitted)\n```\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 5 × 1\n  .fitted\n    <dbl>\n1 -0.0608\n2  0.0756\n3  0.473 \n4  0.560 \n5  0.563 \n```\n\n\n:::\n:::\n\n\n. . .\n\n**For observation 1**\n\n$$\\text{predicted odds} = \\hat{\\text{odds}} = \\frac{\\hat{p}}{1-\\hat{p}} = e^{-0.0608} = 0.941$$\n\n## Predicted probabilities\n\n<br>\n\n::: question\nThe predicted log-odds for observation 1 is -0.0608. What is the predicted probability this respondent is concerned about increased use of AI in daily life?\n:::\n\n## Predicted probabilities {.midi}\n\nWe can calculate predicted probabilities using the argument `type = \"response\"` in `predict.glm()`[^2]\n\n[^2]: The default is `type = \"link\"`, which produces the predicted log-odds.\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\npredict.glm(ai_concern_full_fit, type = \"response\")\n```\n:::\n\n\nShowing the predictions for the first 10 observations\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output .cell-output-stdout}\n\n```\n        1         2         3         4         5         6         7         8 \n0.4848067 0.5188941 0.6161912 0.6364755 0.6371220 0.6366698 0.6159500 0.5257991 \n        9        10 \n0.4898898 0.6329262 \n```\n\n\n:::\n:::\n\n\n## Predicted probability for new observation {.midi}\n\n<br>\n\n::: question\nRecall the model that includes predictors `age_cat`, `ai_heard`, and `survey_time`.\n\n-   What are the predicted odds for a 70-year-old respondent who has heard nothing about AI and took 60 minutes to complete the survey?\n-   What is the predicted probability this respondent is **not** concerned about increased use of AI in daily life?\n-   Would you classify this person as someone who is concerned or someone who is not? Why?\n:::\n\n## Predicted probability for new observation\n\n\n::: {.cell layout-align=\"center\"}\n\n```{.r .cell-code}\nnew_obs <- tibble(age_cat = \"65+\", ai_heard = \"Nothing at all\",  \n                  survey_time = 60)\n\npredict.glm(ai_concern_full_fit, newdata = new_obs, \n            type = \"response\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n        1 \n0.4780527 \n```\n\n\n:::\n:::\n\n\n## Recap\n\n-   Use the odds ratio to compare the odds of two groups\n\n-   Interpret the coefficients of a logistic regression model with\n\n    -   a single categorical predictor\n    -   a single quantitative predictor\n    -   multiple predictors\n\n## References\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}